import {useColorScheme} from 'react-native';

export const COLORS = {
  Primary: '#002366',
  lightBlue: '#F0F8FF',
  White: '#FFFFFF',
  Black: '#000000',
  TextInputBorder: 'rgba(37, 37, 37, 0.2)',
};
const palette = {
  tealGreen: '#128c7e',
  tealGreenDark: '#075e54',
  green: '#25d366',
  lime: '#dcf8c6',
  skyblue: '#34b7f1',
  smokeWhite: '#ece5dd',
  white: 'white',
  gray: '#3C3C3C',
  lightGray: '#757575',
  iconGray: '#717171',
};

export const GetTheme = () => {
  const colorMode = useColorScheme();

  return colorMode === 'light'
    ? {
        BackgroundColor: '#D9D9D9',
        Primary: '#002366',
        lightBlue: '#F0F8FF',
        White: '#FFFFFF',
        Black: '#000000',
        InputBorder: 'rgba(37, 37, 37, 0.2)',
        BlackAndWhite: '#000000',
        WhiteAndBlack: '#FFFFFF',
        mainThemeBackgroundColor: '#ffffff',
        mainThemeForegroundColor: '#3875e8',
        receiverBackgroud: '#DCF7C5',
        mainTextColor: '#151723',
        mainSubtextColor: '#7e7e7e',
        hairlineColor: '#e0e0e0',
        grey0: '#eaeaea',
        grey3: '#e6e6f2',
        grey6: '#d6d6d6',
        grey9: '#939393',
        tint: '#3068CC',
        facebook: '#4267b2',
        grey: 'grey',
        whiteSmoke: '#f5f5f5',
        headerTintColor: '#000000',
        bottomTintColor: 'grey',
        mainButtonColor: '#e8f1fd',
        subButtonColor: '#eaecf0',
        TypeMessageBubble: '#ededed',
        foreground: palette.tealGreenDark,
        tertiary: palette.lime,
        secondary: palette.green,
        white: palette.white,
        secondaryText: palette.lightGray,
        iconGray: palette.iconGray,
        background: '#ffffff',
        alertBackground: '#ffffff',
        text: '#000000',
        primary: '#0505ca',
        border: '#d2d2d2',
        card: 'red',
        checkBackGroundColor: 'grey',
        headerTheme: '#242541',
        WHITE: '#FFFFFF',
      }
    : {
        BackgroundColor: '#D9D9D9',
        Primary: '#002366',
        lightBlue: 'grey',
        White: '#000000',
        Black: '#000000',
        InputBorder: 'rgba(37, 37, 37, 0.2)',
        BlackAndWhite: '#FFFFFF',
        WhiteAndBlack: '#000000',
        mainThemeBackgroundColor: '#121212',
        mainThemeForegroundColor: '#3875e8',
        receiverBackgroud: '#DCF7C5',
        mainTextColor: '#ffffff',
        mainSubtextColor: '#f5f5f5',
        hairlineColor: '#222222',
        tint: '#3068CC',
        facebook: '#4267b2',
        grey: 'grey',
        whiteSmoke: '#222222',
        headerTintColor: '#ffffff',
        bottomTintColor: 'lightgrey',
        mainButtonColor: '#062246',
        subButtonColor: '#20242d',
        TypeMessageBubble: '#4F4F4F',
        foreground: palette.tealGreenDark,
        tertiary: palette.lime,
        secondary: palette.green,
        white: palette.white,
        secondaryText: palette.lightGray,
        iconGray: palette.iconGray,
        background: '#000000',
        alertBackground: '#424242',
        text: '#FFFFFF',
        primary: '#0505ca',
        border: '#d2d2d2',
        card: 'orange',
        checkBackGroundColor: '#000000',
        headerTheme: '#128c7e',
        WHITE: '#FFFFFF',
        grey9: '#bbbfbb',
      };
};
