
export const FONTS = {
  OpenSans_Regular:"OpenSans_Regular",
  OpenSans_Light:"OpenSans_Light",
  OpenSans_Bold:"OpenSans_Bold",
  OpenSans_Medium:"OpenSans_Medium",
// OpenSans_Condensed_Bold:"OpenSans_Condensed-Bold",
// OpenSans_Condensed_BoldItalic:"OpenSans_Condensed-BoldItalic",
// OpenSans_Condensed_ExtraBold:"OpenSans_Condensed_ExtraBold",
// OpenSans_Condensed_ExtraBoldItalic:"OpenSans_Condensed_ExtraBoldItalic",
// OpenSans_Condensed_Italic:"OpenSans_Condensed_Italic",
// OpenSans_Condensed_Light:"OpenSans_Condensed_Light",
// OpenSans_Condensed_LightItalic:"OpenSans_Condensed_LightItalic",
// OpenSans_Condensed_Medium:"OpenSans_Condensed_Medium",
// OpenSans_Condensed_MediumItalic:"OpenSans_Condensed_MediumItalic",
// OpenSans_Condensed_Regular:"OpenSans_Condensed_Regular",
// OpenSans_Condensed_SemiBold:"OpenSans_Condensed_SemiBold",
// OpenSans_Condensed_SemiBoldItalic:"OpenSans_Condensed_SemiBoldItalic",
// OpenSans_SemiCondensed_Bold:"OpenSans_SemiCondensed_Bold",
// OpenSans_SemiCondensed_BoldItalic:"OpenSans_SemiCondensed_BoldItalic",
// OpenSans_SemiCondensed_ExtraBold:"OpenSans_SemiCondensed_ExtraBold",
// OpenSans_SemiCondensed_ExtraBoldItalic:"OpenSans_SemiCondensed_ExtraBoldItalic",
// OpenSans_SemiCondensed_Italic:"OpenSans_SemiCondensed_Italic",
// OpenSans_SemiCondensed_Light:"OpenSans_SemiCondensed_Light",
// OpenSans_SemiCondensed_LightItalic:"OpenSans_SemiCondensed_LightItalic",
// OpenSans_SemiCondensed_Medium:"OpenSans_SemiCondensed_Medium",
// OpenSans_SemiCondensed_MediumItalic:"OpenSans_SemiCondensed_MediumItalic",
// OpenSans_SemiCondensed_Regular:"OpenSans_SemiCondensed_Regular",
// OpenSans_SemiCondensed_SemiBold:"OpenSans_SemiCondensed_SemiBold",
// OpenSans_SemiCondensed_SemiBoldItalic:"OpenSans_SemiCondensed_SemiBoldItalic",
// OpenSans_BoldItalic:"OpenSans_BoldItalic",
// OpenSans_ExtraBold:"OpenSans_ExtraBold",
// OpenSans_ExtraBoldItalic:"OpenSans_ExtraBoldItalic",
// OpenSans_Italic:"OpenSans_Italic",
// OpenSans_LightItalic:"OpenSans_LightItalic",
// OpenSans_MediumItalic:"OpenSans_MediumItalic",
// OpenSans_SemiBold:"OpenSans_SemiBold",
// OpenSans_SemiBoldItalic:"OpenSans_SemiBoldItalic",

  };